import "@/styles/globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { fontSans } from "@/config/fonts";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/providers/query-provider";
// components
import ManagedModal from "@/components/ui/modal/managed-modal";
import { ModalProvider } from "@/components/ui/modal/modal-context";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", fontSans.className)}>
        <Providers>
          <QueryProvider>
            <ModalProvider>
              {children}
              <ManagedModal />
            </ModalProvider>
          </QueryProvider>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
